service: rembg

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-1
  memorySize: 128

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: lambda_function.lambda_handler
    dockerizePip: true
    zip: true
    slim: true
    strip: false
    noDeploy:
      - docutils
      - jmespath
      - pip
      - python-dateutil
      - setuptools
      - six
      - tensorboard
    useStaticCache: true
    useDownloadCache: true
    cacheLocation: "./cache"

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**
    - lambda-rembg/**
    - list/**
    - examples/**
    - cache/**
    - test/**
    - __pycache__/**
    - .pytest_cache/**
    - model/**

functions:
  lambda_function:
    handler: wsgi.lambda_handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'